"""
Every measured number from the project, in one place.

Provenance: all figures were produced on the development machine (Mac Studio, M4
Max, gmsh via pip, OpenCASCADE) by the tools named alongside each block. They are
transcribed here so RESEARCH.md and the slide deck cannot drift apart, and so a
reader can see exactly which tool produced which figure.
"""

# ---------------------------------------------------------------------------
# Three-way mesher comparison -- tools/compare_meshers.py
# Identical FaceBoundary (fingerprint-asserted), identical target size,
# identical quality evaluator. "ideal" = area / (sqrt(3)/4 h^2).
# ---------------------------------------------------------------------------
MESHER_COMPARISON = [
    # case, target, ideal, method, tris, shape_min, shape_mean, min_angle, chord_h, state
    ("plane",       0.15, 103, "Parametric CDT",   140, 0.628, 0.901, 30.3, 0.0,    "closed"),
    ("plane",       0.15, 103, "Parametric AF",    106, 0.692, 0.952, 28.3, 0.0,    "closed"),
    ("plane",       0.15, 103, "Direct 3D AF",     102, 0.477, 0.948, 19.5, 0.0,    "closed"),
    ("L-shape",     0.30,  77, "Parametric CDT",   100, 0.689, 0.906, 27.4, 0.0,    "closed"),
    ("L-shape",     0.30,  77, "Parametric AF",     82, 0.063, 0.925,  3.1, 0.0,    "closed"),
    ("L-shape",     0.30,  77, "Direct 3D AF",      82, 0.063, 0.922,  3.1, 0.0,    "closed"),
    ("cylinder",    1.00, 115, "Parametric CDT",   172, 0.677, 0.916, 31.0, 0.0195, "closed"),
    ("cylinder",    1.00, 115, "Parametric AF",    116, 0.630, 0.956, 25.9, 0.0204, "closed"),
    ("cylinder",    1.00, 115, "Direct 3D AF",     116, 0.681, 0.946, 28.2, 0.0173, "closed"),
    ("sphere band", 1.50, 149, "Parametric CDT",   212, 0.630, 0.888, 26.8, 0.0377, "closed"),
    ("sphere band", 1.50, 149, "Parametric AF",    156, 0.516, 0.962, 21.1, 0.0454, "closed"),
    ("sphere band", 1.50, 149, "Direct 3D AF",     158, 0.290, 0.948, 13.4, 0.0432, "closed"),
    ("sphere pole", 1.50,  78, "Parametric CDT",   128, 0.535, 0.886, 19.3, 0.0337, "closed"),
    ("sphere pole", 1.50,  78, "Parametric AF",    100, 0.136, 0.862,  4.5, 0.4412, "STALL(6)"),
    ("sphere pole", 1.50,  78, "Direct 3D AF",      82, 0.602, 0.930, 21.9, 0.0435, "closed"),
]

# ---------------------------------------------------------------------------
# Metric normalization ablation -- tools/compare_meshers.py --no-linearize
# Cylinder R=10, target 1.0. Metric = diag(100, 1), anisotropy 10.
# ---------------------------------------------------------------------------
METRIC_ABLATION = {
    "raw (u,v)":        {"shape_min": 0.087, "shape_mean": 0.354, "min_angle": 3.1,
                         "tris": 134, "area_err_pct": 0.96},
    "metric-normalized": {"shape_min": 0.654, "shape_mean": 0.866, "min_angle": 28.4,
                          "tris": 42, "area_err_pct": 0.09},
    "ideal_tris": 29,
}

# ---------------------------------------------------------------------------
# Synthetic corpus, production backend -- tools/verify_backend.py
# Six parts generated by tools/make_test_parts.py, each targeting one finding.
# ---------------------------------------------------------------------------
SYNTHETIC_BACKEND = [
    # part, faces, interface_faces, tris, valid, score, shape_min, min_angle,
    # size_in_band, gradation, watertight, est_elements, actual/est, seconds
    ("block_hole",   11, 0,   3506, True,  1.000, 0.776, 31.6, 0.995, 1.36, True,   2547, 1.38, 0.07),
    ("cylinder",      3, 0,   1812, True,  1.000, 0.849, 39.5, 1.000, 1.19, True,   1687, 1.07, 0.02),
    ("sliver_block",  8, 0,  10386, False, 0.000, 0.030,  1.4, 0.648, 1.93, True,   1820, 5.71, 0.21),
    ("sphere",        1, 0,   1120, True,  1.000, 0.721, 31.8, 1.000, 1.19, True,   1047, 1.07, 0.02),
    ("thin_plate",    6, 0, 189844, True,  1.000, 0.600, 27.7, 0.986, 1.13, True, 185129, 1.03, 1.56),
    ("two_blocks",   11, 1,   1650, True,  1.000, 0.899, 42.8, 1.000, 1.23, True,   1470, 1.12, 0.01),
]

# ---------------------------------------------------------------------------
# ABC corpus -- 49 CAD files pulled from one ABC chunk, plus 8 synthetic and
# 3 gmsh sample files present in the same directory. 46 pipeline runs completed.
# Stage 0 triage: tools/... triage.sh ; profile from stage0 JSON reports.
# ---------------------------------------------------------------------------
ABC_TRIAGE = {"clean": 38, "error": 7, "timeout": 2, "block": 2}

ABC_PROFILE = {
    "parsed": 40, "files": 49,
    "scale_min": 3.695, "scale_med": 86.6, "scale_max": 13790.0,
    "faces_min": 1, "faces_med": 30, "faces_max": 894,
}

ABC_STAGE0_FINDINGS = [
    ("discretization.interface_edge", 455),
    ("face.sliver",                   399),
    ("param.distorted",               180),
    ("curve.degenerate",              173),
    ("param.degenerate",              166),
    ("discretization.seam_edge",      133),
    ("discretization.reference",       39),
    ("thickness.measured",             39),
    ("discretization.empty_curve",     32),
    ("discretization.free_edge",       32),
    ("curve.tiny",                     26),
    ("assembly.imprinted",              9),
]

# Four successive corpus runs, each after fixing one class of silent early-return
# in the adaptive loop. This is the debugging record, not a tuning sweep.
ABC_RUN_HISTORY = [
    # label, accepted, plateau, budget, no_action, backend_error, escalated,
    # adapted(iters>1), exported
    ("Run 1\nbaseline",              24,  7, 0, 14, 0, 1,  8, 31),
    ("Run 2\n+empty/budget",         24,  7, 5,  9, 0, 1,  8, 31),
    ("Run 3\n+mesher exception",     24,  8, 6,  1, 6, 1, 10, 31),
    ("Run 4\n+thickness non-fatal",  25, 13, 6,  1, 0, 1, 16, 33),
]

ABC_FINAL = {
    "runs": 46,
    "outcomes": [("accepted", 25), ("score_plateau", 13), ("budget_exhausted", 6),
                 ("no_action_available", 1), ("escalated", 1)],
    "failure_codes": [("mesher.failed", 18), ("validity.degenerate_shape", 3),
                      ("contract.unapproved_removal", 2),
                      ("contract.boundary_mismatch", 1)],
    "unsatisfied": [("min_angle", 9), ("min_shape", 8), ("max_angle", 7)],
    "tris_med": 18410, "tris_max": 228854,
    "sec_med": 4.2, "sec_max": 296.6,
    "adapted": 16, "exported": 33,
}

ABC_SLOWEST = [
    ("00001576_...step_000", 296.6, "no_action_available"),
    ("00003483_...step_000", 180.7, "score_plateau"),
    ("00002307_...step_007",  91.1, "score_plateau"),
    ("00002135_...step_005",  55.8, "score_plateau"),
    ("00006595_...step_000",  52.4, "score_plateau"),
]

# ---------------------------------------------------------------------------
# Threshold calibration -- tools/calibrate.py collect
# ---------------------------------------------------------------------------
CALIBRATION = {
    "total_findings": 780,
    "borderline": 111,
    "by_threshold": [("sliver_circularity", 399), ("distortion_ratio_warn", 180),
                     ("degenerate_curve_frac", 173), ("tiny_curve_frac", 26),
                     ("tiny_face_area_frac", 2)],
    "borderline_ratio_range": (0.51, 0.59),
}

# ---------------------------------------------------------------------------
# Closed-form metric validation -- tests/test_research_quality.py,
# tests/test_quality_framework.py
# ---------------------------------------------------------------------------
CHORDAL_VALIDATION = [
    # target, max edge, measured chordal, sagitta(R=10, maxL), ratio
    (2.0, 2.5000, 0.049958, 0.078433, 0.637),
    (1.0, 1.2869, 0.019525, 0.020723, 0.942),
    (0.5, 0.6442, 0.005130, 0.005189, 0.988),
]

# Circularity separates thin from small; area cannot.
SLIVER_SEPARATION = [
    # description, area, area/scale^2, circularity, aspect, auto-approved
    ("sliver_block rail 50x0.005", 0.25,   4.24e-05, 3.14e-04, 10000, True),
    ("30x1.5 fillet strip",       45.0,    7.63e-03, 1.42e-01,    20, False),
    ("0.001x0.001 patch",          1e-06,  1.69e-10, 7.85e-01,     1, True),
]

# ---------------------------------------------------------------------------
# Repository inventory -- measured, not estimated
# ---------------------------------------------------------------------------
PACKAGES = [
    ("stage0",   1375, 10, "CAD geometry audit; deterministic, no LLM"),
    ("quality",  1166,  5, "Backend-independent evaluation; the arbiter"),
    ("pipeline", 2791,  9, "Entity IDs, size field, policy, loop, contracts, export"),
    ("backends", 1066,  4, "Gmsh production backend (black box) + CAD surface"),
    ("research", 2227,  9, "Three from-scratch meshers; reference only"),
    ("tools",    2318, 12, "CLI drivers, verification, calibration, corpus runner"),
    ("tests",    5011, 14, "300 tests, all runnable without gmsh"),
]

TEST_COUNTS = [
    ("test_loop", 56), ("test_backend", 41), ("test_contracts", 30),
    ("test_quality_framework", 24), ("test_research_kernel", 20),
    ("test_entities", 19), ("test_research_af", 18), ("test_export", 17),
    ("test_research_cdt", 17), ("test_research_quality", 15),
    ("test_geometry_metrics", 12), ("test_gmsh_reference", 12),
    ("test_topology", 11), ("test_metric", 8),
]
TOTAL_TESTS = 300
